### PR TITLE
Colored prefixes on chatbot streaming

### PR DESCRIPTION
**Pull request by lionelchg**
A few tweaks on the chatbot_with_streaming.py script:

- Colored user and assistant prefixes
- Black formatting on script
- Add temperature parameter

An example can be found in the screenshot below:
Screenshot 2023-12-14 at 12 56 47

### CODE REVIEW

**Comment by Bam4d** [comment]
#11 Has been merged, so feel free to rebase!

**Comment by lionelchg** [comment]
Hey just solve the conflicts with `main` branch. I have added colors whenever the model variable pops so that a typical chat now looks like this:

Screenshot 2023-12-19 at 12 24 54

**Comment by Bam4d** [comment]
Hi @lionelchg, did you still want to contribute these changes? They have failing linting and are a bit out of date.

Thanks

**Comment by lionelchg** [comment]
I have merged the updated main and the linting is now OK!

**Pull request closed without merging**
