### PR TITLE
Add support for the deletion of fine-tuned models

### PR DESCRIPTION
**Pull request by arresejo**
Adding support for deleting fine-tuned models.

In the future, it may be beneficial to create a dedicated client specifically for handling model-related tasks such as listing and deletion. If you require any assistance with this, please don't hesitate to ask :-)

### CODE REVIEW

**Review by jean-malo — CHANGES_REQUESTED** [review]
hi @arresejo thanks for the PR, much appreciated!

Could you run ruff and also update the example `async_jobs_chat.py` to include the deletion of the created model ? 

Thanks

**Comment by arresejo** [comment]
Thanks @jean-malo, It should be fixed now

**Comment by jean-malo** [comment]
closing in favor of https://github.com/mistralai/client-python/pull/104 which fixes ruff + prepares the 0.4.1 release

**Comment by jean-malo** [comment]
thank you @arresejo !

**Pull request closed without merging**
