### PR TITLE
Relaxed httpx version requirement (#73).

### PR DESCRIPTION
**Pull request by Mastikosa**
- Dependency of httpx set to be equal or greater that current and less that 1.
- Tested in project where upstream repository could not be added due to dependency conflict.

### CODE REVIEW

**Comment by FAbrahamDev** [comment]
+1

**Comment by ManuelAngel99** [comment]
+1

**Review by baceituno — APPROVED** [review]
pls merge this

**Comment by fuegoio** [comment]
Sorry for the delay in response and thank you for your contribution :)

**Pull request merged**
